CREATE DATABASE tasked;
CREATE USER 'tasked'@'%' IDENTIFIED WITH mysql_native_password BY 'tasked';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, REFERENCES ON tasked.* TO 'tasked'@'%';
